### ISSUE TITLE
Pmag GUI 3.17.0 Standalone does not work

### ISSUE THREAD

**Issue by sslotznick** [PmagPy/PmagPy-Standalone-OSX#6]
Unzipped on a MacOS 10.12.6.  Clicked on program, it tried to open (showed up in bottom bar) then simply disappeared.    Pmag GUI 3.16.0 was able to be opened.

**Comment by moonshoes87** [comment]
Thanks for the bug report.  I'll try to resolve this ASAP.

**Comment by moonshoes87** [comment]
@sslotznick, Pmag GUI 3.17.0 works normally for me, with OS X 10.13.4.  So that's perplexing.  

I'm generating a new version of Pmag GUI 3.17 with some slightly different parameters.  If you can go to the latest release and download Pmag GUI 3.17.2., please try it out!

**Comment by sslotznick** [comment]
@moonshoes87 I tried it out and still doesn't work.  Sounds like it could be a problem with my computer although I restarted it (in case that was an issue).

**Comment by moonshoes87** [comment]
@sslotznick, if I could ask you for a little more debugging help.  I've uploaded Pmag GUI 3.17.3, which must be run from Terminal.  

- Open Terminal
- run pmag_gui, outputting all errors/messages to a file.  So, if Pmag GUI is in your Downloads folder:
`~/Downloads/pmag_gui_3.17.3 &> errors.out`

Hopefully this will produce some useful error output for me.  If you can upload the errors.out file here, that would be great (or email it to ljonestrask@ucsd.edu).

**Comment by moonshoes87** [comment]
Sorry this took so long.  I'm completely mystified by this output, I've posted a question on stackoverflow.com and we'll see if anyone else has any ideas.  

https://stackoverflow.com/questions/49908236/pyinstaller-executable-fails-on-old-os-x

If not, I'll think about some other debugging options.

**Comment by moonshoes87** [comment]
I did a little more digging.  Basically, it appears that you have to compile on an old version of OS X in order to ensure that the executable will run on an old version of OS X.

Info about pyinstaller with old OS X:
https://github.com/pyinstaller/pyinstaller/issues/3418
https://github.com/pyinstaller/pyinstaller/issues/1191
https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible

I'm going to investigate setting up a virtual machine to create a reliable standalone for older versions of OS X.  

How to virtual machine:
https://www.howtogeek.com/304866/how-to-make-linux-and-macos-virtual-machines-for-free-with-parallels-lite/

Getting old versions of OS X:
https://forums.developer.apple.com/message/125106#125106
https://www.apple.com/shop/product/MC573Z/A/mac-os-x-106-snow-leopard

**Comment by moonshoes87** [comment]
For the moment, the answer is just that the PmagPy OS X standalone is only supported on 10.13 (High Sierra) and higher.  I'm still working on creating a version that is supported on older versions, but I can't guarantee when/if that will be available.

I'll update the description of the standalone, and sorry for the inconvenience!

**Comment by moonshoes87** [comment]
Unfortunately, Apple won't provide old operating systems to develop on.  This seems completely idiotic to me, but it means that it really isn't practical to provide standalones for older OSX systems.
